# Generated by Django 5.2 on 2025-08-20 10:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name')),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number', regex='^\\d{10}$')], verbose_name='Phone Number')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Birth Of Date')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile Picture')),
                ('highest_education', models.CharField(blank=True, max_length=100, null=True, verbose_name='Highest Education')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Skills')),
                ('experience_years', models.PositiveIntegerField(blank=True, default=0, verbose_name='Experience Years')),
                ('current_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Position')),
                ('preferred_job_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Preferred Job Location')),
                ('resume_upload', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Resume Upload')),
                ('linkedin_profile', models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile')),
                ('portfolio_link', models.URLField(blank=True, null=True, verbose_name='Portfolio Link')),
                ('project_link', models.URLField(blank=True, null=True, verbose_name='Project Link')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Detail',
                'verbose_name_plural': 'User Details',
                'ordering': ['full_name'],
            },
        ),
    ]
