# Generated by Django 5.2 on 2025-10-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_savedjob_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='profile_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
