# Generated by Django 5.2 on 2025-08-26 09:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number', regex='^\\d{10}$')], verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn Profile')),
                ('github', models.URLField(blank=True, verbose_name='GitHub Link')),
                ('portfolio', models.URLField(blank=True, verbose_name='Portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=200, null=True, verbose_name='Company Name')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Role / Position')),
                ('duration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Duration')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Job Description')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='resume_app.resume', verbose_name='Resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100, verbose_name='Degree')),
                ('university', models.CharField(max_length=200, verbose_name='University')),
                ('year', models.CharField(max_length=10, verbose_name='Year of Passing')),
                ('grade', models.CharField(max_length=20, verbose_name='Grade / CGPA')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='resume_app.resume', verbose_name='Resume')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Skill Name')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume_app.resume', verbose_name='Resume')),
            ],
        ),
    ]
