# Generated by Django 5.2 on 2025-08-28 06:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Skill'),
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number', regex='^\\d{10}$')], verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn Profile')),
                ('github', models.URLField(blank=True, verbose_name='GitHub Profile')),
                ('portfolio', models.URLField(blank=True, verbose_name='Portfolio Website')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50, verbose_name='Language')),
                ('proficiency', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('fluent', 'Fluent'), ('native', 'Native')], max_length=20, verbose_name='Proficiency')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='resume_app.personalinfo', verbose_name='Resume')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Certification Name')),
                ('organization', models.CharField(max_length=200, verbose_name='Issued By')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('credential_id', models.CharField(blank=True, max_length=100, verbose_name='Credential ID')),
                ('credential_url', models.URLField(blank=True, verbose_name='Credential URL')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='resume_app.personalinfo', verbose_name='Resume')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='resume_app.personalinfo', verbose_name='Resume')),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='resume_app.personalinfo', verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='resume_app.personalinfo', verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume_app.personalinfo', verbose_name='Resume'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('technologies', models.CharField(blank=True, max_length=200, verbose_name='Technologies Used')),
                ('link', models.URLField(blank=True, verbose_name='Project Link / GitHub')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='resume_app.personalinfo', verbose_name='Resume')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Publication Title')),
                ('journal', models.CharField(blank=True, max_length=200, verbose_name='Journal / Conference')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Publication Date')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='resume_app.personalinfo', verbose_name='Resume')),
            ],
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
