# Generated by Django 5.2 on 2025-08-28 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_remove_skill_name_skill_skill_personalinfo_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='resume_app.personalinfo', verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='resume_app.personalinfo', verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='resume_app.personalinfo', verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='resume_app.personalinfo', verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='language',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='resume_app.personalinfo', verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='project',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='resume_app.personalinfo', verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='resume_app.personalinfo', verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume_app.personalinfo', verbose_name='Resume'),
        ),
    ]
