# Generated by Django 5.2 on 2025-08-28 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_alter_achievement_resume_alter_certification_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Grade / CGPA'),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='University'),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Year of Passing'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub Profile'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number', regex='^\\d{10}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='portfolio',
            field=models.URLField(blank=True, null=True, verbose_name='Portfolio Website'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Project Link / GitHub'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Technologies Used'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Project Title'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Journal / Conference'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
    ]
