# Generated by Django 5.2 on 2025-08-30 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='category',
            field=models.CharField(choices=[('it', 'IT / Software'), ('civil', 'Civil Engineering'), ('mechanical', 'Mechanical Engineering'), ('electronic', 'Electronics / Electrical'), ('chemical', 'Chemical Engineering'), ('biotech', 'Biotechnology'), ('healthcare', 'Healthcare / Medical'), ('finance', 'Finance / Banking'), ('marketing', 'Marketing / Sales'), ('hr', 'Human Resources'), ('education', 'Education / Teaching'), ('research', 'Research / Development'), ('design', 'Graphic / UX / UI Design'), ('legal', 'Legal / Law'), ('hospitality', 'Hospitality / Tourism'), ('media', 'Media / Journalism'), ('telecom', 'Telecommunications'), ('consulting', 'Consulting'), ('manufacturing', 'Manufacturing'), ('logistics', 'Logistics / Supply Chain'), ('others', 'Other')], default='it', max_length=100, verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job_app.jobdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
    ]
